version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: mac-pro-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'aaa'
    ports:
      - 3309:3306
    # volumes:
      # - ./docker/my.cnf:/etc/mysql/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    restart: always
    environment:
      - PMA_ARBITRARY 1
      - PMA_HOST 127.0.0.1
      - PMA_PORT 3307
      - PMA_USER root
      - PMA_PASSWORD password
      - MYSQL_ROOT_PASSWORD password
